[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200