[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"

  [functions."api"]
  included_files = ["./functions/**", "./src/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200